"""Банк вопросов для игры «Кто хочет стать миллионером» (Millionaire).

Вопросы — на изучение и улучшение английского: лексика, грамматика, предлоги,
фразовые глаголы, идиомы, типичные ошибки. Сложность растёт по тирам (1 — легче,
5 — сложнее), примерно A2 → C1. Каждый вопрос — один правильный вариант из четырёх
плюс короткое объяснение (показывается игроку после ответа/через подсказку).
"""
import random

# Число вопросов из каждого тира в одной партии (5 тиров × 3 = 15).
QUESTIONS_PER_TIER = 3
TOTAL_TIERS = 5


def _q(tier: int, prompt: str, correct: str, distractors: tuple, explanation: str) -> dict:
    """Собрать вопрос: варианты перемешиваются, индекс правильного ответа вычисляется сам.

    Позволяет писать банк компактно и без ручной индексации правильного варианта.
    """
    options = [correct, *distractors]
    random.shuffle(options)
    return {
        "tier": tier,
        "prompt": prompt,
        "options": options,
        "answer": options.index(correct),
        "explanation": explanation,
    }

# Каждый вопрос: tier (1..5), prompt, options (ровно 4), answer (индекс 0..3),
# explanation (короткое пояснение на английском).
MILLIONAIRE_QUESTIONS: list[dict] = [
    # ------------------------------------------------------------- тир 1 (A2)
    {"tier": 1, "prompt": "Choose the correct word: “She ___ to work every day.”",
     "options": ["go", "goes", "going", "gone"], "answer": 1,
     "explanation": "“She” is third person singular, so we add -s: “goes”."},
    {"tier": 1, "prompt": "“I ___ a book right now.”",
     "options": ["read", "reads", "am reading", "is reading"], "answer": 2,
     "explanation": "“Right now” signals the present continuous: “am reading”."},
    {"tier": 1, "prompt": "“There ___ three cats in the garden.”",
     "options": ["is", "are", "be", "am"], "answer": 1,
     "explanation": "“Three cats” is plural, so we use “are”."},
    {"tier": 1, "prompt": "“___ you like coffee?”",
     "options": ["Do", "Does", "Are", "Is"], "answer": 0,
     "explanation": "With “you” we use “Do” in the present simple question."},
    {"tier": 1, "prompt": "“He is ___ honest man.”",
     "options": ["a", "an", "the", "—"], "answer": 1,
     "explanation": "“Honest” starts with a vowel sound, so we use “an”."},
    {"tier": 1, "prompt": "“We went to the park ___ Sunday.”",
     "options": ["in", "on", "at", "for"], "answer": 1,
     "explanation": "We use “on” with days of the week."},
    {"tier": 1, "prompt": "“This is my friend. ___ name is Tom.”",
     "options": ["His", "Her", "Its", "Their"], "answer": 0,
     "explanation": "Tom is male, so the possessive is “his”."},
    {"tier": 1, "prompt": "“How ___ apples do you want?”",
     "options": ["much", "many", "any", "some"], "answer": 1,
     "explanation": "“Apples” is countable, so we use “many”."},
    {"tier": 1, "prompt": "“I have two ___.”",
     "options": ["child", "childs", "children", "childrens"], "answer": 2,
     "explanation": "“Child” has the irregular plural “children”."},
    {"tier": 1, "prompt": "“___ is the weather like today?”",
     "options": ["How", "What", "Which", "Where"], "answer": 1,
     "explanation": "The fixed phrase is “What is the weather like?”."},
    {"tier": 1, "prompt": "“My sister ___ TV every evening.”",
     "options": ["watch", "watches", "watching", "is watch"], "answer": 1,
     "explanation": "Third person singular in the present simple: “watches”."},
    {"tier": 1, "prompt": "“___ you from Spain?”",
     "options": ["Is", "Are", "Do", "Does"], "answer": 1,
     "explanation": "“You” takes “Are”: “Are you from Spain?”."},
    {"tier": 1, "prompt": "“I ___ coffee in the morning.”",
     "options": ["don't drink", "doesn't drink", "not drink", "am not drink"], "answer": 0,
     "explanation": "“I” takes “don't” in the negative present simple."},
    {"tier": 1, "prompt": "“The children ___ playing outside now.”",
     "options": ["is", "are", "be", "am"], "answer": 1,
     "explanation": "“Children” is plural, so we use “are”."},
    {"tier": 1, "prompt": "“There is ___ milk in the fridge.”",
     "options": ["some", "any", "a few", "many"], "answer": 0,
     "explanation": "We use “some” in positive sentences with uncountable nouns."},
    {"tier": 1, "prompt": "“I don't have ___ money.”",
     "options": ["some", "any", "a", "many"], "answer": 1,
     "explanation": "We use “any” in negative sentences."},
    {"tier": 1, "prompt": "“She lives ___ London.”",
     "options": ["at", "on", "in", "for"], "answer": 2,
     "explanation": "We use “in” with cities and countries."},
    {"tier": 1, "prompt": "“I get up ___ seven o'clock.”",
     "options": ["in", "on", "for", "at"], "answer": 3,
     "explanation": "We use “at” with exact times."},
    {"tier": 1, "prompt": "“He goes to work ___ car.”",
     "options": ["by", "on", "in", "with"], "answer": 0,
     "explanation": "“By” is used with means of transport: “by car”."},
    {"tier": 1, "prompt": "“___ old are you?”",
     "options": ["What", "How", "Which", "Who"], "answer": 1,
     "explanation": "“How old” asks about age."},
    {"tier": 1, "prompt": "“We ___ to the cinema yesterday.”",
     "options": ["go", "goes", "went", "gone"], "answer": 2,
     "explanation": "“Yesterday” signals the past simple: “went”."},
    {"tier": 1, "prompt": "“Can you ___ me, please?”",
     "options": ["to help", "help", "helping", "helps"], "answer": 1,
     "explanation": "After “can” we use the base form: “help”."},
    {"tier": 1, "prompt": "“She ___ a doctor.”",
     "options": ["am", "are", "is", "be"], "answer": 2,
     "explanation": "“She” takes “is”."},
    {"tier": 1, "prompt": "“Look! It ___ outside.”",
     "options": ["rain", "rains", "is raining", "are raining"], "answer": 2,
     "explanation": "“Look!” signals the present continuous: “is raining”."},
    {"tier": 1, "prompt": "“I like ___ football.”",
     "options": ["play", "to playing", "playing", "plays"], "answer": 2,
     "explanation": "“Like” is followed by -ing: “playing”."},
    {"tier": 1, "prompt": "“The cat is ___ the table.”",
     "options": ["under", "on", "in", "at"], "answer": 0,
     "explanation": "“Under” means directly below something."},
    {"tier": 1, "prompt": "“___ your brother like ice cream?”",
     "options": ["Do", "Does", "Is", "Are"], "answer": 1,
     "explanation": "“Your brother” is third person singular, so we use “Does”."},
    {"tier": 1, "prompt": "“This is ___ house.”",
     "options": ["we", "us", "our", "ours"], "answer": 2,
     "explanation": "“Our” is the possessive adjective before a noun."},
    {"tier": 1, "prompt": "“I am ___ student.”",
     "options": ["a", "an", "the", "—"], "answer": 0,
     "explanation": "“Student” starts with a consonant sound, so we use “a”."},
    {"tier": 1, "prompt": "“We usually ___ lunch at one.”",
     "options": ["have", "has", "having", "to have"], "answer": 0,
     "explanation": "“We” takes the base form “have”."},
    _q(1, "“My parents ___ doctors.”", "are", ("is", "am", "be"), "“Parents” is plural, so we use “are”."),
    _q(1, "“___ you have any brothers?”", "Do", ("Does", "Are", "Is"), "With “you” we use “Do” in questions."),
    _q(1, "“She ___ a new car.”", "has", ("have", "is", "haves"), "“She” takes “has” (third person singular)."),
    _q(1, "“We ___ at home yesterday.”", "were", ("was", "is", "are"), "“Yesterday” + plural subject → “were”."),
    _q(1, "“I ___ born in 1990.”", "was", ("were", "am", "is"), "“I” takes “was” in the past."),
    _q(1, "“___ he like reading?”", "Does", ("Do", "Is", "Are"), "Third person singular question → “Does”."),
    _q(1, "“There ___ a book on the table.”", "is", ("are", "be", "am"), "“A book” is singular, so we use “is”."),
    _q(1, "“I can ___ English.”", "speak", ("to speak", "speaking", "speaks"), "After “can” we use the base form."),
    _q(1, "“She is ___ than her sister.”", "taller", ("tall", "tallest", "more tall"), "Comparative of “tall” is “taller”."),
    _q(1, "“This is ___ apple.”", "an", ("a", "the", "—"), "“Apple” starts with a vowel sound, so we use “an”."),
    _q(1, "“We ___ to music now.”", "are listening", ("listen", "listens", "is listening"), "“Now” + plural subject → present continuous “are listening”."),
    _q(1, "“He ___ his homework every day.”", "does", ("do", "doing", "is doing"), "Third person singular of “do” is “does”."),
    _q(1, "“___ is your birthday?”", "When", ("What", "Who", "Why"), "“When” asks about time."),
    _q(1, "“___ do you live?”", "Where", ("What", "Who", "When"), "“Where” asks about place."),
    _q(1, "“The sun ___ in the east.”", "rises", ("rise", "rising", "is rise"), "Third person singular: “rises”."),
    _q(1, "“She goes to school ___ bus.”", "by", ("on", "in", "with"), "“By bus” is the correct phrase for transport."),
    _q(1, "“I have ___ orange.”", "an", ("a", "the", "—"), "“Orange” starts with a vowel sound → “an”."),
    _q(1, "“They ___ from Italy.”", "are", ("is", "am", "be"), "“They” takes “are”."),
    _q(1, "“___ you want some tea?”", "Do", ("Does", "Are", "Is"), "“You” takes “Do”."),
    _q(1, "“He ___ fast.”", "runs", ("run", "running", "is run"), "Third person singular: “runs”."),
    _q(1, "“We ___ TV last night.”", "watched", ("watch", "watching", "watches"), "Past simple of “watch” is “watched”."),
    _q(1, "“She ___ a letter yesterday.”", "wrote", ("write", "writes", "writing"), "Irregular past of “write” is “wrote”."),
    _q(1, "“The book is ___ the table.”", "on", ("in", "at", "under"), "“On” means resting on the surface."),
    _q(1, "“I go to bed ___ night.”", "at", ("in", "on", "for"), "“At night” is the fixed phrase."),
    _q(1, "“___ many students in the class?”", "Are there", ("Is there", "There are", "There is"), "Plural → “Are there”."),
    _q(1, "“My father works ___ a hospital.”", "in", ("on", "at", "by"), "“In a hospital” — we use “in” with buildings."),
    _q(1, "“I ___ a shower every morning.”", "take", ("make", "do", "takes"), "The phrase is “take a shower”."),
    _q(1, "“She ___ to music every day.”", "listens", ("listen", "listening", "is listen"), "Third person singular: “listens”."),
    _q(1, "“This car is ___.”", "new", ("newly", "news", "newer"), "“New” is the adjective describing the car."),
    _q(1, "“___ you open the window?”", "Can", ("Do", "Are", "Is"), "“Can” asks about ability or a request."),
    _q(1, "“He is ___ student at my school.”", "a", ("an", "the", "—"), "“Student” starts with a consonant sound → “a”."),
    _q(1, "“I don't ___ coffee.”", "like", ("likes", "liking", "to like"), "Negative present simple: “don't + base form”."),
    _q(1, "“She ___ a beautiful song.”", "sang", ("sing", "sings", "singed"), "Irregular past of “sing” is “sang”."),
    _q(1, "“We ___ friends.”", "are", ("is", "am", "be"), "“We” takes “are”."),
    _q(1, "“The children ___ in the garden.”", "are playing", ("is playing", "play", "plays"), "Plural + now → present continuous “are playing”."),
    _q(1, "“I have ___ homework today.”", "some", ("any", "a", "many"), "Positive sentence with uncountable noun → “some”."),
    _q(1, "“There isn't ___ bread.”", "any", ("some", "a", "many"), "Negative sentence → “any”."),
    _q(1, "“___ time is it?”", "What", ("How", "Which", "When"), "“What time” asks for the clock time."),
    _q(1, "“She ___ the piano.”", "plays", ("play", "playing", "is play"), "Third person singular: “plays”."),
    _q(1, "“I ___ a new bike.”", "have", ("has", "having", "am having"), "“I” takes “have”."),
    _q(1, "“He is taller ___ me.”", "than", ("then", "that", "as"), "Comparative uses “than”."),
    _q(1, "“___ do you usually get up?”", "When", ("What", "Where", "Which"), "“When” asks about time."),
    _q(1, "“We're going ___ the cinema.”", "to", ("at", "in", "on"), "“Go to” a place."),
    _q(1, "“She was born ___ May.”", "in", ("on", "at", "for"), "“In” is used with months."),
    _q(1, "“I'll see you ___ Monday.”", "on", ("in", "at", "for"), "“On” is used with days."),
    _q(1, "“The cat is sleeping ___ the sofa.”", "on", ("in", "at", "under"), "“On” for a surface like a sofa."),
    _q(1, "“___ sisters do you have?”", "How many", ("How much", "How old", "How long"), "“Sisters” is countable → “How many”."),
    _q(1, "“She ___ to the shop every day.”", "goes", ("go", "going", "gone"), "Third person singular: “goes”."),
    _q(1, "“This is ___ interesting book.”", "an", ("a", "the", "—"), "“Interesting” starts with a vowel sound → “an”."),
    _q(1, "“He ___ English at school.”", "studies", ("study", "studying", "is study"), "Third person singular: “studies”."),
    _q(1, "“I ___ a glass of water, please.”", "would like", ("like", "likes", "am liking"), "“Would like” is the polite request form."),
    _q(1, "“They ___ football on Saturdays.”", "play", ("plays", "playing", "is play"), "“They” takes the base form “play”."),
    _q(1, "“She is good ___ dancing.”", "at", ("in", "on", "for"), "The phrase is “good at”."),
    _q(1, "“I am ___ than my brother.”", "older", ("old", "oldest", "more old"), "Comparative of “old” is “older”."),
    _q(1, "“We ___ to the beach last summer.”", "went", ("go", "goes", "gone"), "Irregular past of “go” is “went”."),
    _q(1, "“___ is the nearest bank?”", "Where", ("What", "When", "Who"), "“Where” asks about a place."),
    _q(1, "“He ___ up at six every day.”", "gets", ("get", "getting", "is get"), "Third person singular: “gets”."),
    _q(1, "“There ___ many people at the party.”", "were", ("was", "is", "are"), "Past + plural → “were”."),
    _q(1, "“I ___ some apples.”", "bought", ("buy", "buys", "buying"), "Irregular past of “buy” is “bought”."),
    _q(1, "“She is afraid ___ dogs.”", "of", ("from", "for", "at"), "The phrase is “afraid of”."),
    _q(1, "“___ you like to dance?”", "Do", ("Does", "Are", "Is"), "“You” takes “Do”."),
    _q(1, "“He has ___ dog.”", "a", ("an", "the", "—"), "“Dog” starts with a consonant sound → “a”."),
    _q(1, "“I ___ breakfast at eight.”", "have", ("has", "having", "am having"), "“I” takes “have”."),
    _q(1, "“The lesson starts ___ nine.”", "at", ("in", "on", "for"), "“At” is used with exact times."),
    _q(1, "“She ___ her teeth twice a day.”", "brushes", ("brush", "brushing", "is brush"), "Third person singular: “brushes”."),
    _q(1, "“We are ___ the bus stop.”", "at", ("in", "on", "for"), "“At” is used with a point/location."),
    _q(1, "“I ___ to buy a new phone.”", "want", ("wants", "wanting", "to wanting"), "“I” takes the base form “want”."),
    _q(1, "“He is sitting ___ the chair.”", "on", ("in", "at", "under"), "“On” for sitting on a chair."),
    _q(1, "“___ you help me with my homework?”", "Can", ("Do", "Are", "Is"), "“Can” asks for help/ability."),
    _q(1, "“She ___ a cup of tea every morning.”", "drinks", ("drink", "drinking", "is drink"), "Third person singular: “drinks”."),

    # ------------------------------------------------------------- тир 2 (B1)
    {"tier": 2, "prompt": "“I ___ my homework yet.”",
     "options": ["didn't do", "haven't done", "doesn't do", "hadn't done"], "answer": 1,
     "explanation": "“Yet” is used with the present perfect: “haven't done”."},
    {"tier": 2, "prompt": "“This book is ___ than that one.”",
     "options": ["more interesting", "interesting", "most interesting", "interester"], "answer": 0,
     "explanation": "For long adjectives the comparative is “more interesting”."},
    {"tier": 2, "prompt": "“She has lived here ___ 2015.”",
     "options": ["for", "since", "during", "from"], "answer": 1,
     "explanation": "We use “since” with a point in time, “for” with a duration."},
    {"tier": 2, "prompt": "“I look forward ___ from you.”",
     "options": ["to hear", "hearing", "to hearing", "hear"], "answer": 2,
     "explanation": "“Look forward to” is followed by a noun or -ing: “to hearing”."},
    {"tier": 2, "prompt": "“If it ___, we will stay home.”",
     "options": ["rain", "rains", "will rain", "raining"], "answer": 1,
     "explanation": "First conditional: “if + present simple, will + verb”."},
    {"tier": 2, "prompt": "“You ___ smoke here. It's forbidden.”",
     "options": ["don't have to", "mustn't", "couldn't", "should"], "answer": 1,
     "explanation": "“Mustn't” expresses prohibition (it is not allowed)."},
    {"tier": 2, "prompt": "“The meeting was cancelled ___ the bad weather.”",
     "options": ["because", "because of", "so", "although"], "answer": 1,
     "explanation": "“Because of” is followed by a noun phrase: “the bad weather”."},
    {"tier": 2, "prompt": "“I'm used to ___ early.”",
     "options": ["get up", "getting up", "got up", "gets up"], "answer": 1,
     "explanation": "“Be used to” is followed by -ing: “getting up”."},
    {"tier": 2, "prompt": "“Could you tell me where ___?”",
     "options": ["is the station", "the station is", "the station", "does the station"], "answer": 1,
     "explanation": "Indirect questions use normal word order: “the station is”."},
    {"tier": 2, "prompt": "“He asked me if I ___ him.”",
     "options": ["can help", "could help", "will help", "have helped"], "answer": 1,
     "explanation": "Reported speech shifts “can” to “could”."},
    {"tier": 2, "prompt": "“I ___ my keys. I can't find them.”",
     "options": ["lose", "have lost", "am losing", "was losing"], "answer": 1,
     "explanation": "A past action with a present result → present perfect: “have lost”."},
    {"tier": 2, "prompt": "“This is the ___ film I've ever seen.”",
     "options": ["good", "better", "best", "most good"], "answer": 2,
     "explanation": "“Ever” calls for the superlative: “the best”."},
    {"tier": 2, "prompt": "“We ___ go to the beach tomorrow.”",
     "options": ["will", "are going to", "went", "go"], "answer": 1,
     "explanation": "A fixed plan for the future → “are going to”."},
    {"tier": 2, "prompt": "“I've known him ___ we were children.”",
     "options": ["for", "since", "during", "ago"], "answer": 1,
     "explanation": "“Since” + a clause/point in time: “since we were children”."},
    {"tier": 2, "prompt": "“You ___ wear a uniform at school.”",
     "options": ["must to", "have to", "has to", "mustn't"], "answer": 1,
     "explanation": "Obligation from rules → “have to” (you = “have”)."},
    {"tier": 2, "prompt": "“I ___ swim when I was five.”",
     "options": ["can", "could", "will can", "may"], "answer": 1,
     "explanation": "Past ability → “could”."},
    {"tier": 2, "prompt": "“He gave ___ smoking last year.”",
     "options": ["up", "off", "in", "out"], "answer": 0,
     "explanation": "“Give up” = stop doing something."},
    {"tier": 2, "prompt": "“I'm looking ___ my keys.”",
     "options": ["after", "for", "at", "to"], "answer": 1,
     "explanation": "“Look for” = search for."},
    {"tier": 2, "prompt": "“She said she ___ tired.”",
     "options": ["is", "was", "be", "were"], "answer": 1,
     "explanation": "Reported speech shifts present to past: “was”."},
    {"tier": 2, "prompt": "“I have ___ friends in this city.”",
     "options": ["a few", "much", "little", "a little"], "answer": 0,
     "explanation": "“Friends” is countable, so we use “a few”."},
    {"tier": 2, "prompt": "“There aren't ___ people here.”",
     "options": ["some", "many", "much", "a few"], "answer": 1,
     "explanation": "“People” is countable, so we use “many”."},
    {"tier": 2, "prompt": "“Would you like ___ tea?”",
     "options": ["any", "some", "many", "a few"], "answer": 1,
     "explanation": "In offers/requests we use “some”."},
    {"tier": 2, "prompt": "“The film starts ___ 7 p.m.”",
     "options": ["on", "in", "at", "for"], "answer": 2,
     "explanation": "“At” is used with exact times."},
    {"tier": 2, "prompt": "“I'm interested ___ art.”",
     "options": ["in", "on", "at", "for"], "answer": 0,
     "explanation": "The adjective pattern is “interested in”."},
    {"tier": 2, "prompt": "“She's good ___ maths.”",
     "options": ["in", "at", "on", "with"], "answer": 1,
     "explanation": "The phrase is “good at” something."},
    {"tier": 2, "prompt": "“I'm tired ___ waiting.”",
     "options": ["of", "for", "with", "at"], "answer": 0,
     "explanation": "The phrase is “tired of” + -ing."},
    {"tier": 2, "prompt": "“He's afraid ___ spiders.”",
     "options": ["from", "of", "for", "at"], "answer": 1,
     "explanation": "The phrase is “afraid of”."},
    {"tier": 2, "prompt": "“I haven't seen him ___ last week.”",
     "options": ["for", "since", "during", "at"], "answer": 1,
     "explanation": "“Since” + a point in time: “since last week”."},
    {"tier": 2, "prompt": "“She ___ to the gym twice a week.”",
     "options": ["go", "goes", "is going", "gone"], "answer": 1,
     "explanation": "A regular habit → present simple, “she” → “goes”."},
    {"tier": 2, "prompt": "“If you ___ harder, you'll pass.”",
     "options": ["study", "studies", "will study", "studied"], "answer": 0,
     "explanation": "First conditional: “if + present simple”."},
    _q(2, "“I ___ TV when she called.”", "was watching", ("watched", "watch", "am watching"), "A longer past action interrupted by another → past continuous."),
    _q(2, "“He has never ___ to Paris.”", "been", ("gone", "went", "go"), "“Have been to” = visited and returned."),
    _q(2, "“She's been working here ___ three years.”", "for", ("since", "during", "ago"), "“For” + a duration."),
    _q(2, "“If it rains, we ___ home.”", "will stay", ("stay", "stayed", "would stay"), "First conditional: “will + verb”."),
    _q(2, "“You ___ worry; it's fine.”", "don't have to", ("mustn't", "can't", "shouldn't"), "“Don't have to” = it is not necessary."),
    _q(2, "“This is the ___ restaurant in town.”", "best", ("good", "better", "most good"), "Superlative of “good” is “best”."),
    _q(2, "“I'm going ___ a party tonight.”", "to", ("at", "in", "for"), "“Go to” an event."),
    _q(2, "“She's ___ person I know.”", "the kindest", ("kinder", "kind", "the kinder"), "Superlative: “the kindest”."),
    _q(2, "“We ___ a great time last week.”", "had", ("have", "has", "having"), "Past of “have a great time” is “had”."),
    _q(2, "“I've ___ finished my homework.”", "just", ("yet", "already", "still"), "“Just” = a short time ago (present perfect)."),
    _q(2, "“He ___ to the gym every day last year.”", "went", ("goes", "go", "has gone"), "“Last year” → past simple “went”."),
    _q(2, "“___ you ever been to London?”", "Have", ("Did", "Do", "Are"), "“Have you ever been” — present perfect."),
    _q(2, "“She ___ her leg and couldn't walk.”", "broke", ("broke up", "has broken", "breaks"), "Irregular past of “break” is “broke”."),
    _q(2, "“I used to ___ in the countryside.”", "live", ("living", "lived", "to live"), "“Used to” is followed by the base form."),
    _q(2, "“He's interested ___ history.”", "in", ("on", "at", "for"), "The phrase is “interested in”."),
    _q(2, "“The film was ___ than I expected.”", "better", ("good", "best", "more good"), "Comparative of “good” is “better”."),
    _q(2, "“I'd like ___ coffee, please.”", "some", ("any", "a", "many"), "In offers/requests we use “some”."),
    _q(2, "“She ___ the bus every morning.”", "catches", ("catch", "catching", "is catch"), "Third person singular: “catches”."),
    _q(2, "“You ___ be tired after the trip.”", "must", ("can", "should", "might"), "“Must” = strong deduction."),
    _q(2, "“I'm not ___ in sport.”", "interested", ("interesting", "interest", "interests"), "A person is “interested”."),
    _q(2, "“He ___ asleep during the film.”", "fell", ("felt", "falled", "fall"), "Past of “fall asleep” is “fell asleep”."),
    _q(2, "“We're meeting ___ Friday.”", "on", ("in", "at", "for"), "“On” with days of the week."),
    _q(2, "“She has ___ here since 2005.”", "lived", ("live", "living", "lives"), "Present perfect with “since”."),
    _q(2, "“I ___ my phone at home.”", "left", ("leaved", "leave", "have left"), "Past of “leave” is “left”."),
    _q(2, "“The concert ___ at eight.”", "starts", ("start", "starting", "is start"), "Timetabled event → present simple."),
    _q(2, "“Could you ___ me a favour?”", "do", ("make", "give", "take"), "The phrase is “do a favour”."),
    _q(2, "“She's fed up ___ her job.”", "with", ("of", "for", "at"), "The phrase is “fed up with”."),
    _q(2, "“I'm looking forward ___ the holidays.”", "to", ("for", "at", "in"), "“Look forward to”."),
    _q(2, "“He ___ a lot of money last year.”", "earned", ("earn", "earning", "has earned"), "Past simple “earned”."),
    _q(2, "“___ you mind closing the door?”", "Would", ("Do", "Are", "Could"), "“Would you mind + -ing” is polite."),
    _q(2, "“I'm sure they'll ___.”", "come", ("coming", "came", "to come"), "After “will” we use the base form."),
    _q(2, "“She ___ me she was ill.”", "told", ("said", "sayed", "tell"), "“Tell someone” (with an object) → “told”."),
    _q(2, "“He asked me ___ I was busy.”", "if", ("what", "that", "do"), "Reported yes/no questions use “if”."),
    _q(2, "“I've been waiting ___ an hour.”", "for", ("since", "during", "ago"), "“For” + a duration."),
    _q(2, "“You ___ see a doctor.”", "should", ("must to", "could to", "shoulds"), "“Should” gives advice."),
    _q(2, "“We ___ go if the weather's good.”", "might", ("might to", "must to", "can to"), "“Might” expresses possibility."),
    _q(2, "“She's really good ___ languages.”", "at", ("in", "on", "for"), "The phrase is “good at”."),
    _q(2, "“I can't decide ___ to wear.”", "what", ("which", "that", "who"), "“What to wear” = the right question form."),
    _q(2, "“He's been studying ___ five hours.”", "for", ("since", "during", "ago"), "“For” + a duration."),
    _q(2, "“I ___ when you called.”", "was cooking", ("cooked", "cook", "am cooking"), "Interrupted past action → past continuous."),
    _q(2, "“The train leaves ___ 10:30.”", "at", ("in", "on", "for"), "“At” with exact times."),
    _q(2, "“She's worked here ___ 2010.”", "since", ("for", "during", "in"), "“Since” + a point in time."),
    _q(2, "“I'm ___ of the dark.”", "afraid", ("frightened", "scared", "fear"), "The phrase is “afraid of”."),
    _q(2, "“He's been ill ___ last Monday.”", "since", ("for", "during", "from"), "“Since” + a point in time."),
    _q(2, "“I ___ a new job last month.”", "got", ("get", "gotten", "have got"), "Past of “get” is “got”."),
    _q(2, "“We'll have dinner ___ we get home.”", "when", ("while", "during", "until"), "“When” introduces a time clause."),
    _q(2, "“She is ___ than me.”", "more patient", ("patient", "most patient", "patienter"), "Long adjective → “more patient”."),
    _q(2, "“I ___ to the radio when I drive.”", "listen", ("listen to", "hears", "listens"), "“Listen to” the radio."),
    _q(2, "“He ___ his car washed yesterday.”", "had", ("made", "did", "has"), "Causative “have + object + past participle”."),
    _q(2, "“___ you like to come with us?”", "Would", ("Do", "Are", "Could"), "“Would you like” is the polite offer."),
    _q(2, "“She's very ___; everyone likes her.”", "friendly", ("friend", "friends", "friendlier"), "“Friendly” is the adjective."),
    _q(2, "“I've lost ___ keys.”", "my", ("mine", "me", "myself"), "Possessive adjective before a noun: “my”."),
    _q(2, "“We ___ a film when the power went out.”", "were watching", ("watched", "watch", "was watching"), "Interrupted past action, plural → “were watching”."),
    _q(2, "“I ___ coffee for three years.”", "haven't drunk", ("didn't drink", "don't drink", "won't drink"), "“For three years” → present perfect negative."),
    _q(2, "“He works ___ a nurse.”", "as", ("like", "for", "at"), "“Work as” a profession."),
    _q(2, "“I'm not very good ___ cooking.”", "at", ("in", "on", "for"), "The phrase is “good at”."),
    _q(2, "“She ___ the exam last week.”", "passed", ("pass", "passing", "has passed"), "Past simple “passed”."),
    _q(2, "“We've ___ to Italy twice.”", "been", ("gone", "went", "be"), "“Have been to” = visited."),
    _q(2, "“I'd rather ___ at home tonight.”", "stay", ("to stay", "staying", "stayed"), "“Would rather” + base form."),
    _q(2, "“He said he ___ come tomorrow.”", "would", ("will", "can", "shall"), "Reported speech shifts “will” to “would”."),
    _q(2, "“I'm used to ___ coffee in the morning.”", "drinking", ("drink", "drank", "to drink"), "“Be used to” + -ing."),
    _q(2, "“She ___ for this company since 2015.”", "has worked", ("works", "worked", "is working"), "“Since 2015” → present perfect."),
    _q(2, "“I ___ him for ten years.”", "have known", ("know", "knew", "am knowing"), "“For ten years” → present perfect."),
    _q(2, "“It's getting ___ outside.”", "dark", ("darkly", "darkness", "darker"), "“Get + adjective” = become; “dark”."),
    _q(2, "“He ___ his keys and couldn't get in.”", "lost", ("lose", "losed", "loses"), "Past of “lose” is “lost”."),
    _q(2, "“We're going to ___ a party.”", "have", ("make", "do", "has"), "The phrase is “have a party”."),
    _q(2, "“She's not ___ to drive yet.”", "allowed", ("allowed to", "allow", "allows"), "“Be allowed to” — here “allowed”."),
    _q(2, "“I ___ you were coming!”", "didn't know", ("don't know", "haven't known", "wasn't know"), "Past negative: “didn't know”."),
    _q(2, "“He's very ___ about his work.”", "proud", ("proudly", "pride", "prouder"), "“Proud of” something."),
    _q(2, "“I'll call you ___ I arrive.”", "when", ("while", "during", "until"), "“When” introduces a time clause."),

    # ------------------------------------------------------------- тир 3 (B2)
    {"tier": 3, "prompt": "“If I ___ you, I would apologize.”",
     "options": ["am", "were", "was", "would be"], "answer": 1,
     "explanation": "Second conditional uses “if I were” (subjunctive)."},
    {"tier": 3, "prompt": "“I wish I ___ more time.”",
     "options": ["have", "had", "will have", "would have"], "answer": 1,
     "explanation": "“Wish + past simple” expresses a present regret: “had”."},
    {"tier": 3, "prompt": "“The cake ___ by my grandmother.”",
     "options": ["was made", "made", "is making", "makes"], "answer": 0,
     "explanation": "Passive voice in the past: “was made”."},
    {"tier": 3, "prompt": "“I'd rather you ___ here.”",
     "options": ["stay", "stayed", "to stay", "staying"], "answer": 1,
     "explanation": "“Would rather + subject + past simple”: “stayed”."},
    {"tier": 3, "prompt": "“She has been working here ___.”",
     "options": ["for five years", "since five years", "during five years", "ago five years"], "answer": 0,
     "explanation": "“For” is used with a duration: “for five years”."},
    {"tier": 3, "prompt": "“___ the film was boring, we stayed until the end.”",
     "options": ["Although", "Despite", "However", "Because"], "answer": 0,
     "explanation": "“Although” introduces a clause; “despite” needs a noun/-ing."},
    {"tier": 3, "prompt": "“He denied ___ the money.”",
     "options": ["to steal", "stealing", "steal", "steals"], "answer": 1,
     "explanation": "“Deny” is followed by -ing: “stealing”."},
    {"tier": 3, "prompt": "“This is the man ___ car was stolen.”",
     "options": ["who", "which", "whose", "whom"], "answer": 2,
     "explanation": "“Whose” shows possession: the man's car."},
    {"tier": 3, "prompt": "“By the time we arrived, the train ___.”",
     "options": ["left", "has left", "had left", "was left"], "answer": 2,
     "explanation": "“By the time + past” → past perfect: “had left”."},
    {"tier": 3, "prompt": "“She suggested ___ to the cinema.”",
     "options": ["to go", "going", "go", "went"], "answer": 1,
     "explanation": "“Suggest” is followed by -ing: “going”."},
    {"tier": 3, "prompt": "“If I had known, I ___ you.”",
     "options": ["will tell", "would tell", "would have told", "tell"], "answer": 2,
     "explanation": "Third conditional: “would have + past participle”."},
    {"tier": 3, "prompt": "“The letter ___ yesterday.”",
     "options": ["sent", "was sent", "is sent", "has sent"], "answer": 1,
     "explanation": "Past passive: “was sent”."},
    {"tier": 3, "prompt": "“I ___ rather stay home.”",
     "options": ["had", "would", "should", "will"], "answer": 1,
     "explanation": "The phrase is “would rather”."},
    {"tier": 3, "prompt": "“It's important ___ on time.”",
     "options": ["being", "to be", "be", "is"], "answer": 1,
     "explanation": "“It's important to + infinitive”: “to be”."},
    {"tier": 3, "prompt": "“I can't help ___ when I see that film.”",
     "options": ["to laugh", "laughing", "laugh", "laughed"], "answer": 1,
     "explanation": "“Can't help” is followed by -ing: “laughing”."},
    {"tier": 3, "prompt": "“The book, ___ I bought yesterday, is great.”",
     "options": ["that", "which", "who", "whose"], "answer": 1,
     "explanation": "In a non-defining clause we use “which”."},
    {"tier": 3, "prompt": "“I wish I ___ that.”",
     "options": ["didn't say", "hadn't said", "won't say", "haven't said"], "answer": 1,
     "explanation": "A past regret → “wish + past perfect”: “hadn't said”."},
    {"tier": 3, "prompt": "“He ___ be at home; the lights are on.”",
     "options": ["must", "can't", "shouldn't", "mightn't"], "answer": 0,
     "explanation": "“Must” expresses strong logical deduction."},
    {"tier": 3, "prompt": "“You ___ have told me earlier!”",
     "options": ["must", "should", "will", "can"], "answer": 1,
     "explanation": "“Should have” criticizes a past action."},
    {"tier": 3, "prompt": "“This cake tastes ___.”",
     "options": ["delicious", "deliciously", "well", "nicely"], "answer": 0,
     "explanation": "“Taste” is a linking verb, followed by an adjective."},
    {"tier": 3, "prompt": "“I'm not used to ___ in a big city.”",
     "options": ["live", "living", "to live", "lived"], "answer": 1,
     "explanation": "“Be used to” + -ing: “living”."},
    {"tier": 3, "prompt": "“The more you practice, ___ you get.”",
     "options": ["the best", "the better", "better", "more good"], "answer": 1,
     "explanation": "Comparative structure: “the more … the better”."},
    {"tier": 3, "prompt": "“I ___ for you for two hours.”",
     "options": ["wait", "have been waiting", "am waiting", "waited"], "answer": 1,
     "explanation": "Duration up to now → present perfect continuous."},
    {"tier": 3, "prompt": "“He was accused ___ the crime.”",
     "options": ["of", "for", "with", "about"], "answer": 0,
     "explanation": "The pattern is “accused of” something."},
    {"tier": 3, "prompt": "“She's responsible ___ the project.”",
     "options": ["of", "for", "with", "to"], "answer": 1,
     "explanation": "The phrase is “responsible for”."},
    {"tier": 3, "prompt": "“The house was ___ by a famous architect.”",
     "options": ["designed", "design", "designing", "designs"], "answer": 0,
     "explanation": "Past passive: “was designed”."},
    {"tier": 3, "prompt": "“If only I ___ more time.”",
     "options": ["have", "had", "will have", "would have"], "answer": 1,
     "explanation": "“If only + past simple” = a present wish."},
    {"tier": 3, "prompt": "“They insisted ___ paying the bill.”",
     "options": ["in", "on", "at", "for"], "answer": 1,
     "explanation": "The pattern is “insist on” + -ing."},
    {"tier": 3, "prompt": "“She's been studying English ___ 2018.”",
     "options": ["for", "since", "during", "in"], "answer": 1,
     "explanation": "“Since” + a point in time: “since 2018”."},
    {"tier": 3, "prompt": "“She's ___ to get married next year.”",
     "options": ["go", "going", "gone", "went"], "answer": 1,
     "explanation": "A plan: “is going to” + verb."},
    _q(3, "“If I ___ enough money, I'd travel more.”", "had", ("have", "would have", "will have"), "Second conditional uses the past simple: “had”."),
    _q(3, "“The project was completed ___ time.”", "on", ("in", "at", "for"), "The phrase is “on time” = punctually."),
    _q(3, "“She insisted ___ speaking to the manager.”", "on", ("in", "at", "for"), "“Insist on” + -ing."),
    _q(3, "“I'm looking forward ___ from you.”", "to hearing", ("to hear", "hearing", "hear"), "“Look forward to” + -ing."),
    _q(3, "“He ___ have left; his coat is gone.”", "must", ("can", "should", "might"), "“Must have” = a strong deduction about the past."),
    _q(3, "“The report was ___ by the committee.”", "approved", ("approve", "approving", "approves"), "Past passive: “was approved”."),
    _q(3, "“I wish I ___ to the party last night.”", "had gone", ("went", "have gone", "would go"), "A past regret → “wish + past perfect”."),
    _q(3, "“She's ___ to arrive any minute.”", "due", ("about", "bound", "ready"), "“Be due to” = expected at a set time."),
    _q(3, "“The book is worth ___.”", "reading", ("to read", "read", "to reading"), "“Worth” is followed by -ing: “worth reading”."),
    _q(3, "“He apologized ___ being late.”", "for", ("of", "about", "to"), "“Apologize for” + -ing."),
    _q(3, "“I'd ___ you didn't smoke.”", "rather", ("better", "sooner", "prefer"), "“Would rather + subject + past simple”."),
    _q(3, "“The meeting ___ until next week.”", "has been postponed", ("postponed", "is postponed", "was postponed"), "Present perfect passive: “has been postponed”."),
    _q(3, "“She's capable ___ doing the job.”", "of", ("to", "for", "in"), "“Capable of” + -ing."),
    _q(3, "“If you ___ me, I'd have helped.”", "had asked", ("asked", "have asked", "would ask"), "Third conditional: “if + past perfect”."),
    _q(3, "“He's suspected ___ the theft.”", "of", ("for", "with", "about"), "“Suspected of” + noun/-ing."),
    _q(3, "“I object ___ being treated like a child.”", "to", ("against", "for", "on"), "“Object to” + noun/-ing."),
    _q(3, "“The house needs ___.”", "painting", ("to paint", "paint", "painted"), "“Need + -ing” has a passive meaning."),
    _q(3, "“She's not used to ___ criticized.”", "being", ("be", "been", "to be"), "“Be used to” + -ing; passive → “being criticized”."),
    _q(3, "“I couldn't help ___ at his joke.”", "laughing", ("to laugh", "laugh", "laughed"), "“Can't help” + -ing."),
    _q(3, "“He ___ me to apply for the job.”", "encouraged", ("encouraged to", "encourage", "encouraging"), "“Encourage someone to do something”."),
    _q(3, "Which word means the same as “happy”?", "cheerful", ("sad", "angry", "tired"), "“Cheerful” means happy and positive."),
    _q(3, "Which word means the same as “begin”?", "commence", ("finish", "stop", "delay"), "“Commence” is a formal synonym of “begin”."),
    _q(3, "Which word means the same as “buy”?", "purchase", ("sell", "borrow", "rent"), "“Purchase” is a formal synonym of “buy”."),
    _q(3, "Which word means the same as “get”?", "obtain", ("lose", "give", "receive"), "“Obtain” means to get or acquire."),
    _q(3, "Which word means the same as “help”?", "assist", ("hinder", "ignore", "harm"), "“Assist” means to help."),
    _q(3, "Which word means the same as “show”?", "demonstrate", ("hide", "deny", "refuse"), "“Demonstrate” means to show clearly."),
    _q(3, "Which word means the same as “big”?", "enormous", ("tiny", "narrow", "short"), "“Enormous” means extremely big."),
    _q(3, "Which word means the same as “fast”?", "rapid", ("slow", "steady", "late"), "“Rapid” means happening quickly."),
    _q(3, "Which word means the same as “small”?", "tiny", ("huge", "broad", "vast"), "“Tiny” means extremely small."),
    _q(3, "Which word means the same as “important”?", "crucial", ("trivial", "minor", "optional"), "“Crucial” means extremely important."),
    _q(3, "Which word means the same as “end”?", "conclude", ("begin", "continue", "start"), "“Conclude” means to finish or end."),
    _q(3, "Which word means the same as “sad”?", "miserable", ("joyful", "content", "glad"), "“Miserable” means very unhappy."),
    _q(3, "Which word means the same as “tell”?", "inform", ("hide", "listen", "doubt"), "“Inform” means to tell or notify."),
    _q(3, "Which word means the same as “allow”?", "permit", ("forbid", "block", "stop"), "“Permit” means to allow."),
    _q(3, "Which word means the same as “enough”?", "sufficient", ("lacking", "short", "sparse"), "“Sufficient” means enough."),
    _q(3, "What does “postpone” mean?", "to delay until later", ("to do now", "to cancel forever", "to speed up"), "“Postpone” = move to a later time."),
    _q(3, "What does “reluctant” mean?", "unwilling to do something", ("eager to help", "excited to start", "afraid to speak"), "“Reluctant” = not wanting to do it."),
    _q(3, "What does “genuine” mean?", "real and not fake", ("broken and old", "new and shiny", "cheap and plain"), "“Genuine” = authentic, real."),
    _q(3, "What does “scarce” mean?", "hard to find", ("easy to see", "all around", "very common"), "“Scarce” = in short supply."),
    _q(3, "What does “assume” mean?", "to think something is true without proof", ("to prove a fact", "to forget quickly", "to ask politely"), "“Assume” = suppose without evidence."),
    _q(3, "What does “achieve” mean?", "to succeed in doing something", ("to fail badly", "to give up", "to plan forever"), "“Achieve” = reach a goal."),
    _q(3, "What does “avoid” mean?", "to stay away from", ("to run toward", "to look for", "to talk about"), "“Avoid” = keep away from."),
    _q(3, "What does “crucial” mean?", "extremely important", ("not needed", "a little useful", "impossible"), "“Crucial” = essential, decisive."),
    _q(3, "What does “distinct” mean?", "clearly different", ("almost the same", "hard to see", "mixed together"), "“Distinct” = separate and clearly different."),
    _q(3, "What does “emphasize” mean?", "to give special importance to", ("to ignore", "to hide", "to reduce"), "“Emphasize” = stress or highlight."),
    _q(3, "What does “evident” mean?", "easy to see", ("impossible to find", "hard to believe", "secret and hidden"), "“Evident” = clear, obvious."),
    _q(3, "What does “imply” mean?", "to suggest without saying directly", ("to state clearly", "to deny", "to shout"), "“Imply” = hint at something."),
    _q(3, "What does “maintain” mean?", "to keep something going", ("to stop completely", "to forget", "to destroy"), "“Maintain” = keep in good condition."),
    _q(3, "What does “perceive” mean?", "to notice or understand", ("to ignore", "to misunderstand", "to avoid"), "“Perceive” = become aware of."),
    _q(3, "What does “resolve” mean?", "to find a solution to", ("to create a problem", "to delay", "to forget"), "“Resolve” = solve, settle."),
    _q(3, "Choose the correct sentence.", "She suggested going home.", ("She suggested to go home.", "She suggested go home.", "She suggested to going home."), "“Suggest” is followed by -ing."),
    _q(3, "Choose the correct sentence.", "If I were you, I'd apologize.", ("If I was you, I'd apologize.", "If I am you, I'd apologize.", "If I would be you, I'd apologize."), "The subjunctive is “if I were you”."),
    _q(3, "Choose the correct sentence.", "The letter was sent yesterday.", ("The letter sent yesterday.", "The letter is send yesterday.", "The letter has sent yesterday."), "Past passive: “was sent”."),
    _q(3, "Choose the correct sentence.", "He denied stealing the money.", ("He denied to steal the money.", "He denied steal the money.", "He denied steals the money."), "“Deny” is followed by -ing."),
    _q(3, "Choose the correct sentence.", "She has been working here for five years.", ("She has been working here since five years.", "She has worked here since five years.", "She is working here for five years."), "“For” + duration."),
    _q(3, "Choose the correct sentence.", "By the time we arrived, the train had left.", ("By the time we arrived, the train has left.", "By the time we arrived, the train was left.", "By the time we arrived, the train leaves."), "Past perfect: “had left”."),
    _q(3, "Choose the correct sentence.", "I look forward to hearing from you.", ("I look forward to hear from you.", "I look forward hearing from you.", "I look forward to hears from you."), "“Look forward to” + -ing."),
    _q(3, "Choose the correct sentence.", "Despite the rain, we went out.", ("Although the rain, we went out.", "Despite of the rain, we went out.", "Despite it rained, we went out."), "“Despite” is followed by a noun."),
    _q(3, "Choose the correct sentence.", "The more you practice, the better you get.", ("The more you practice, the best you get.", "The more you practice, better you get.", "The more you practice, the more better you get."), "Comparative structure: “the more … the better”."),
    _q(3, "Choose the correct sentence.", "I wish I had more time.", ("I wish I have more time.", "I wish I will have more time.", "I wish I would have more time."), "“Wish + past simple” for a present wish."),
    _q(3, "Choose the correct sentence.", "This is the man whose car was stolen.", ("This is the man who car was stolen.", "This is the man which car was stolen.", "This is the man whom car was stolen."), "“Whose” shows possession."),
    _q(3, "Choose the correct sentence.", "She is said to be a genius.", ("She is said being a genius.", "She is said to being a genius.", "She is said be a genius."), "“Be said to + infinitive”."),
    _q(3, "Choose the correct sentence.", "He insisted on paying the bill.", ("He insisted to pay the bill.", "He insisted on to pay the bill.", "He insisted paying the bill."), "“Insist on” + -ing."),
    _q(3, "Choose the correct sentence.", "I'd rather you stayed here.", ("I'd rather you stay here.", "I'd rather you to stay here.", "I'd rather you staying here."), "“Would rather + subject + past simple”."),
    _q(3, "Choose the correct sentence.", "The house was designed by a famous architect.", ("The house designed by a famous architect.", "The house was design by a famous architect.", "The house was designed from a famous architect."), "Past passive: “was designed by”."),
    _q(3, "Choose the correct sentence.", "She can't help laughing at his jokes.", ("She can't help to laugh at his jokes.", "She can't help laugh at his jokes.", "She can't help laughs at his jokes."), "“Can't help” + -ing."),
    _q(3, "Choose the correct sentence.", "I used to live in the countryside.", ("I used to living in the countryside.", "I used to lived in the countryside.", "I use to live in the countryside."), "“Used to” + base form."),
    _q(3, "Choose the correct sentence.", "He has never been to Paris.", ("He has never went to Paris.", "He have never been to Paris.", "He has never was to Paris."), "Present perfect: “has been”."),
    _q(3, "Choose the correct sentence.", "The meeting was called off due to bad weather.", ("The meeting was called of due to bad weather.", "The meeting was called off due of bad weather.", "The meeting called off due to bad weather."), "“Call off” = cancel; “due to”."),
    _q(3, "Choose the correct sentence.", "You should have told me earlier.", ("You should told me earlier.", "You should have tell me earlier.", "You should of told me earlier."), "“Should have + past participle”."),

    # ------------------------------------------------------------- тир 4 (B2+)
    {"tier": 4, "prompt": "“___ the rain, we went out anyway.”",
     "options": ["Despite", "Although", "However", "Because"], "answer": 0,
     "explanation": "“Despite” is followed by a noun: “the rain”."},
    {"tier": 4, "prompt": "“I regret ___ at you. I was angry.”",
     "options": ["to shout", "shouting", "having shouted", "shouted"], "answer": 1,
     "explanation": "“Regret + -ing” = regret a past action: “shouting”."},
    {"tier": 4, "prompt": "“Hardly ___ the door when the phone rang.”",
     "options": ["had I closed", "I had closed", "did I close", "I closed"], "answer": 0,
     "explanation": "“Hardly … when” triggers inversion: “had I closed”."},
    {"tier": 4, "prompt": "“The project ___ by next month.”",
     "options": ["will finish", "will be finished", "will have finished", "is finishing"], "answer": 1,
     "explanation": "Future passive: “will be finished”."},
    {"tier": 4, "prompt": "“I'd have helped you if I ___ about it.”",
     "options": ["knew", "had known", "would know", "know"], "answer": 1,
     "explanation": "Third conditional: “if + past perfect”: “had known”."},
    {"tier": 4, "prompt": "“She is believed ___ the race.”",
     "options": ["to win", "to have won", "winning", "win"], "answer": 1,
     "explanation": "Passive reporting + perfect infinitive: “to have won”."},
    {"tier": 4, "prompt": "“Not only ___ late, but he also forgot the report.”",
     "options": ["he was", "was he", "he is", "is he"], "answer": 1,
     "explanation": "“Not only … but also” triggers inversion: “was he”."},
    {"tier": 4, "prompt": "“I can't put ___ with his behavior anymore.”",
     "options": ["up", "off", "on", "down"], "answer": 0,
     "explanation": "“Put up with” = tolerate."},
    {"tier": 4, "prompt": "“The new policy will come ___ force next month.”",
     "options": ["into", "in", "at", "to"], "answer": 0,
     "explanation": "The phrase is “come into force” = become active."},
    {"tier": 4, "prompt": "“He's been feeling ___ the weather lately.”",
     "options": ["under", "over", "behind", "below"], "answer": 0,
     "explanation": "“Under the weather” = slightly ill."},
    {"tier": 4, "prompt": "“___ I were taller, I'd play basketball.”",
     "options": ["If", "When", "Unless", "As"], "answer": 0,
     "explanation": "Second conditional starts with “If”."},
    {"tier": 4, "prompt": "“He got the job ___ his experience.”",
     "options": ["because", "because of", "so", "due"], "answer": 1,
     "explanation": "“Because of” + noun phrase: “his experience”."},
    {"tier": 4, "prompt": "“I'd rather you ___ told me.”",
     "options": ["have", "had", "has", "having"], "answer": 1,
     "explanation": "“Would rather + subject + past perfect” = past regret."},
    {"tier": 4, "prompt": "“The report needs ___ by Friday.”",
     "options": ["to finish", "to be finished", "finishing", "finished"], "answer": 1,
     "explanation": "Passive meaning after “need”: “to be finished”."},
    {"tier": 4, "prompt": "“She is said ___ a genius.”",
     "options": ["to be", "being", "is", "be"], "answer": 0,
     "explanation": "“Be said to + infinitive”: “to be”."},
    {"tier": 4, "prompt": "“Never ___ such a beautiful view.”",
     "options": ["have I seen", "I have seen", "I saw", "did I see"], "answer": 0,
     "explanation": "“Never” at the start triggers inversion: “have I seen”."},
    {"tier": 4, "prompt": "“I look forward to ___ you.”",
     "options": ["see", "seeing", "saw", "seen"], "answer": 1,
     "explanation": "“Look forward to” + -ing: “seeing”."},
    {"tier": 4, "prompt": "“He was made ___ for the damage.”",
     "options": ["pay", "to pay", "paying", "paid"], "answer": 1,
     "explanation": "“Make” in the passive takes “to”: “was made to pay”."},
    {"tier": 4, "prompt": "“The children are used to ___ up early.”",
     "options": ["get", "getting", "got", "to get"], "answer": 1,
     "explanation": "“Be used to” + -ing: “getting up”."},
    {"tier": 4, "prompt": "“___ he arrives, tell him to call me.”",
     "options": ["When", "While", "During", "If only"], "answer": 0,
     "explanation": "“When” introduces a time clause."},
    {"tier": 4, "prompt": "“The film was ___ good that I saw it twice.”",
     "options": ["so", "such", "very", "too"], "answer": 0,
     "explanation": "“So + adjective + that” shows a result."},
    {"tier": 4, "prompt": "“It was ___ a hard exam that everyone failed.”",
     "options": ["so", "such", "very", "too"], "answer": 1,
     "explanation": "“Such + a/an + adjective + noun” shows a result."},
    {"tier": 4, "prompt": "“He works ___ hard that he never rests.”",
     "options": ["so", "such", "very", "too"], "answer": 0,
     "explanation": "“So + adverb + that”: “so hard that”."},
    {"tier": 4, "prompt": "“I'm tired ___ doing the same thing.”",
     "options": ["of", "for", "with", "at"], "answer": 0,
     "explanation": "“Tired of” + -ing."},
    {"tier": 4, "prompt": "“She insisted on ___ the house herself.”",
     "options": ["paint", "painting", "painted", "to paint"], "answer": 1,
     "explanation": "“Insist on” + -ing: “painting”."},
    {"tier": 4, "prompt": "“I can't afford ___ a new car.”",
     "options": ["buy", "buying", "to buy", "bought"], "answer": 2,
     "explanation": "“Afford” is followed by “to + infinitive”: “to buy”."},
    {"tier": 4, "prompt": "“He avoided ___ the question.”",
     "options": ["to answer", "answering", "answer", "answered"], "answer": 1,
     "explanation": "“Avoid” is followed by -ing: “answering”."},
    {"tier": 4, "prompt": "“The manager had the report ___ by his assistant.”",
     "options": ["write", "wrote", "written", "writing"], "answer": 2,
     "explanation": "Causative “have + object + past participle”: “written”."},
    {"tier": 4, "prompt": "“We need to cut ___ on expenses.”",
     "options": ["down", "up", "off", "in"], "answer": 0,
     "explanation": "“Cut down on” = reduce."},
    {"tier": 4, "prompt": "“The deal fell ___ at the last minute.”",
     "options": ["through", "out", "off", "down"], "answer": 0,
     "explanation": "“Fall through” = fail to happen."},
    _q(4, "“He ___ up smoking after ten years.”", "gave", ("took", "made", "put"), "“Give up” = stop doing something."),
    _q(4, "“The plan fell ___ due to costs.”", "through", ("out", "off", "down"), "“Fall through” = fail to happen."),
    _q(4, "“She takes ___ her mother.”", "after", ("over", "up", "on"), "“Take after” = resemble a family member."),
    _q(4, "“I can't make ___ what this says.”", "out", ("up", "off", "in"), "“Make out” = manage to read/understand."),
    _q(4, "“We're running ___ of coffee.”", "out", ("up", "off", "over"), "“Run out of” = have none left."),
    _q(4, "“He's been ___ off at work.”", "laid", ("put", "taken", "set"), "“Lay off” = dismiss from a job."),
    _q(4, "“She ___ over the company last year.”", "took", ("gave", "put", "made"), "“Take over” = gain control of."),
    _q(4, "“The project has been put ___ until March.”", "off", ("on", "up", "in"), "“Put off” = postpone."),
    _q(4, "“I'll look ___ it straight away.”", "into", ("after", "for", "up"), "“Look into” = investigate."),
    _q(4, "“He ___ out to be right after all.”", "turned", ("made", "came", "went"), "“Turn out” = prove to be."),
    _q(4, "“The meeting broke ___ at noon.”", "up", ("down", "off", "in"), "“Break up” = end a meeting/event."),
    _q(4, "“She ___ up with a brilliant idea.”", "came", ("went", "put", "made"), "“Come up with” = think of."),
    _q(4, "“We need to ___ out the details.”", "work", ("make", "take", "put"), "“Work out” = figure out/calculate."),
    _q(4, "“The news ___ him by surprise.”", "took", ("made", "caught", "put"), "“Take someone by surprise” is the phrase."),
    _q(4, "“She ___ on her promise and told everyone.”", "went back", ("went off", "went over", "went out"), "“Go back on a promise” = break a promise."),
    _q(4, "“He has a ___ for getting into trouble.”", "knack", ("habit", "talent", "gift"), "“A knack for” = a natural skill/tendency."),
    _q(4, "“She has a ___ for languages.”", "flair", ("flaw", "flash", "flock"), "“A flair for” = a natural talent for."),
    _q(4, "“He takes great ___ in his work.”", "pride", ("proud", "prideful", "proudly"), "“Take pride in” = be proud of."),
    _q(4, "“The new rule comes ___ effect on Monday.”", "into", ("in", "to", "under"), "“Come into effect” = become active."),
    _q(4, "“He's ___ on the idea of retiring early.”", "keen", ("set", "fond", "eager"), "“Keen on” = enthusiastic about."),
    _q(4, "“She was ___ to tears by the speech.”", "moved", ("made", "taken", "put"), "“Move someone to tears” = make them cry."),
    _q(4, "“The plan is well under ___.”", "way", ("progress", "construction", "development"), "“Under way” = in progress."),
    _q(4, "“She's very ___ of other people's feelings.”", "mindful", ("minding", "mindless", "mindful of"), "“Mindful of” = aware and considerate of."),
    _q(4, "“He ___ his success to hard work.”", "attributes", ("contributes", "distributes", "tributes"), "“Attribute something to” = say it is caused by."),
    _q(4, "“The book was ___ by critics.”", "acclaimed", ("claimed", "exclaimed", "proclaimed"), "“Acclaimed” = publicly praised."),
    _q(4, "What does “meticulous” mean?", "extremely careful about details", ("careless and rushed", "loud and rude", "generous and kind"), "“Meticulous” = very thorough and precise."),
    _q(4, "What does “inevitable” mean?", "certain to happen", ("easy to avoid", "hard to see", "unlikely to occur"), "“Inevitable” = cannot be prevented."),
    _q(4, "What does “feasible” mean?", "possible to do", ("impossible", "too expensive", "against the rules"), "“Feasible” = workable, achievable."),
    _q(4, "What does “coherent” mean?", "clear and logical", ("confused and vague", "broken and weak", "hidden and secret"), "“Coherent” = well-organized, logical."),
    _q(4, "What does “diverse” mean?", "showing great variety", ("all the same", "very small", "poorly organized"), "“Diverse” = varied, mixed."),
    _q(4, "What does “profound” mean?", "very deep and serious", ("shallow and trivial", "loud and angry", "brief and shallow"), "“Profound” = deep, intense."),
    _q(4, "What does “tedious” mean?", "boring and long", ("quick and easy", "fun and exciting", "short and simple"), "“Tedious” = slow and dull."),
    _q(4, "What does “ambiguous” mean?", "having more than one meaning", ("completely clear", "very short", "strictly true"), "“Ambiguous” = unclear, open to interpretation."),
    _q(4, "What does “impartial” mean?", "fair and not biased", ("unfair and one-sided", "angry and hostile", "lazy and slow"), "“Impartial” = neutral, unbiased."),
    _q(4, "What does “plausible” mean?", "likely to be true", ("obviously false", "hard to imagine", "too strange"), "“Plausible” = believable, credible."),
    _q(4, "What does “relentless” mean?", "never stopping", ("easily tired", "gentle and soft", "rarely seen"), "“Relentless” = continuous, persistent."),
    _q(4, "What does “perilous” mean?", "dangerous", ("completely safe", "very easy", "extremely calm"), "“Perilous” = full of danger."),
    _q(4, "What does “frivolous” mean?", "not serious", ("very serious", "extremely important", "deeply meaningful"), "“Frivolous” = silly, lacking seriousness."),
    _q(4, "Which word means the same as “angry”?", "furious", ("calm", "content", "bored"), "“Furious” means extremely angry."),
    _q(4, "Which word means the same as “tired”?", "exhausted", ("energetic", "rested", "lively"), "“Exhausted” means very tired."),
    _q(4, "Which word means the same as “worried”?", "anxious", ("relaxed", "carefree", "calm"), "“Anxious” means worried or uneasy."),
    _q(4, "Which word means the same as “famous”?", "renowned", ("unknown", "obscure", "forgotten"), "“Renowned” means widely known."),
    _q(4, "Which word means the same as “brave”?", "courageous", ("cowardly", "timid", "fearful"), "“Courageous” means brave."),
    _q(4, "Which word means the same as “clean”?", "immaculate", ("dirty", "messy", "filthy"), "“Immaculate” means perfectly clean."),
    _q(4, "Which word means the same as “strange”?", "peculiar", ("ordinary", "common", "normal"), "“Peculiar” means odd or unusual."),
    _q(4, "Which word means the same as “important” (formal)?", "paramount", ("trivial", "minor", "secondary"), "“Paramount” means of the highest importance."),
    _q(4, "Which word means the same as “very old”?", "ancient", ("modern", "recent", "new"), "“Ancient” means extremely old."),
    _q(4, "Choose the correct sentence.", "Hardly had I closed the door when the phone rang.", ("Hardly I had closed the door when the phone rang.", "Hardly did I close the door when the phone rang.", "Hardly I closed the door when the phone rang."), "“Hardly … when” triggers inversion: “had I closed”."),
    _q(4, "Choose the correct sentence.", "Not only was he late, but he also forgot the report.", ("Not only he was late, but he also forgot the report.", "Not only was he late, but he forgot also the report.", "Not only was he late, but also he forgot the report."), "“Not only” triggers inversion: “was he”."),
    _q(4, "Choose the correct sentence.", "Never have I seen such a beautiful view.", ("Never I have seen such a beautiful view.", "Never I saw such a beautiful view.", "Never have I saw such a beautiful view."), "“Never” triggers inversion: “have I seen”."),
    _q(4, "Choose the correct sentence.", "I'd have helped you if I had known about it.", ("I'd have helped you if I knew about it.", "I'd help you if I had known about it.", "I'll have helped you if I had known about it."), "Third conditional: “would have … if + past perfect”."),
    _q(4, "Choose the correct sentence.", "She is believed to have won the race.", ("She is believed to win the race.", "She is believed winning the race.", "She is believed having won the race."), "Perfect infinitive: “to have won”."),
    _q(4, "Choose the correct sentence.", "The project will be finished by next month.", ("The project will finish by next month.", "The project will have finished by next month.", "The project is finishing by next month."), "Future passive: “will be finished”."),
    _q(4, "Choose the correct sentence.", "It was such a hard exam that everyone failed.", ("It was so a hard exam that everyone failed.", "It was such hard exam that everyone failed.", "It was so hard exam that everyone failed."), "“Such a + adjective + noun … that”."),
    _q(4, "Choose the correct sentence.", "He was made to pay for the damage.", ("He was made pay for the damage.", "He was made paying for the damage.", "He was made to paying for the damage."), "“Make” in the passive takes “to”."),
    _q(4, "Choose the correct sentence.", "The manager had the report written by his assistant.", ("The manager had the report write by his assistant.", "The manager had the report wrote by his assistant.", "The manager had the report writing by his assistant."), "Causative “have + object + past participle”."),
    _q(4, "Choose the correct sentence.", "There's little point in arguing about it.", ("There's little point to argue about it.", "There's little point of arguing about it.", "There's little point arguing about it."), "The phrase is “there's little point in -ing”."),
    _q(4, "Choose the correct sentence.", "I'd rather you had told me.", ("I'd rather you have told me.", "I'd rather you told me earlier.", "I'd rather you has told me."), "“Would rather + subject + past perfect” for the past."),
    _q(4, "Choose the correct sentence.", "The report needs to be finished by Friday.", ("The report needs finished by Friday.", "The report needs to finish by Friday.", "The report needs be finished by Friday."), "“Need to be + past participle”."),
    _q(4, "Choose the correct sentence.", "She insisted on painting the house herself.", ("She insisted on to paint the house herself.", "She insisted to paint the house herself.", "She insisted painting the house herself."), "“Insist on” + -ing."),
    _q(4, "Choose the correct sentence.", "I can't afford to buy a new car.", ("I can't afford buying a new car.", "I can't afford buy a new car.", "I can't afford to buying a new car."), "“Afford to + infinitive”."),
    _q(4, "Choose the correct sentence.", "He avoided answering the question.", ("He avoided to answer the question.", "He avoided answer the question.", "He avoided answers the question."), "“Avoid” + -ing."),
    _q(4, "Choose the correct sentence.", "The deal fell through at the last minute.", ("The deal fell off at the last minute.", "The deal fell down at the last minute.", "The deal fell out at the last minute."), "“Fall through” = fail to happen."),
    _q(4, "Choose the correct sentence.", "We need to cut down on expenses.", ("We need to cut up on expenses.", "We need to cut off on expenses.", "We need to cut in on expenses."), "“Cut down on” = reduce."),
    _q(4, "Choose the correct sentence.", "The film was so good that I saw it twice.", ("The film was such good that I saw it twice.", "The film was so a good that I saw it twice.", "The film was too good that I saw it twice."), "“So + adjective + that”."),
    _q(4, "What does “scrupulous” mean?", "very careful to do things correctly", ("careless and sloppy", "greedy and selfish", "loud and rude"), "“Scrupulous” = extremely honest and careful."),
    _q(4, "Which word means the same as “clear”?", "obvious", ("vague", "hidden", "confusing"), "“Obvious” means clear and easy to see."),
    _q(4, "“She pays close ___ to detail.”", "attention", ("attentive", "notice", "care"), "“Pay attention to” is the phrase."),
    _q(4, "“He finally ___ up the courage to speak.”", "summoned", ("made", "took", "got"), "“Summon up the courage” = find the courage."),
    _q(4, "Choose the correct sentence.", "He attributes his success to hard work.", ("He attributes his success with hard work.", "He attributes his success for hard work.", "He attributes his success on hard work."), "“Attribute something to” something."),

    # ------------------------------------------------------------- тир 5 (C1)
    {"tier": 5, "prompt": "“___ the circumstances, we have no choice.”",
     "options": ["Under", "In", "With", "Given"], "answer": 0,
     "explanation": "The fixed phrase is “under the circumstances”."},
    {"tier": 5, "prompt": "“It's high time you ___ a decision.”",
     "options": ["make", "made", "have made", "will make"], "answer": 1,
     "explanation": "“It's (high) time” is followed by the past simple: “made”."},
    {"tier": 5, "prompt": "“She was at ___ for what to say.”",
     "options": ["a loss", "a lose", "loss", "the loss"], "answer": 0,
     "explanation": "“At a loss for words” = unable to think what to say."},
    {"tier": 5, "prompt": "“The results are ___ the final report.”",
     "options": ["pending", "waiting", "depending", "attending"], "answer": 0,
     "explanation": "“Pending” = waiting to be decided or completed."},
    {"tier": 5, "prompt": "“He has an ___ knowledge of French.”",
     "options": ["extensive", "expensive", "extended", "expanded"], "answer": 0,
     "explanation": "The collocation is “extensive knowledge” = broad/deep."},
    {"tier": 5, "prompt": "“___ had she left than he arrived.”",
     "options": ["No sooner", "Rarely", "Not until", "Only"], "answer": 0,
     "explanation": "“No sooner … than” is the fixed pairing."},
    {"tier": 5, "prompt": "“Each of the students ___ a book.”",
     "options": ["have", "has", "are", "having"], "answer": 1,
     "explanation": "“Each of” takes a singular verb: “has”."},
    {"tier": 5, "prompt": "“I'd rather ___ than take the bus.”",
     "options": ["to walk", "walk", "walking", "walked"], "answer": 1,
     "explanation": "“Would rather” is followed by a bare infinitive: “walk”."},
    {"tier": 5, "prompt": "“There's little point ___ arguing about it.”",
     "options": ["in", "of", "for", "on"], "answer": 0,
     "explanation": "The phrase is “there's little point in -ing”."},
    {"tier": 5, "prompt": "“She's cut out ___ teaching.”",
     "options": ["for", "of", "in", "to"], "answer": 0,
     "explanation": "“Be cut out for” = naturally suited to something."},
    {"tier": 5, "prompt": "“The proposal is ___ consideration.”",
     "options": ["under", "in", "on", "at"], "answer": 0,
     "explanation": "The phrase is “under consideration” = being reviewed."},
    {"tier": 5, "prompt": "“He's ___ his head above water.”",
     "options": ["keeping", "holding", "putting", "getting"], "answer": 0,
     "explanation": "“Keep one's head above water” = barely manage financially."},
    {"tier": 5, "prompt": "“The committee ___ to meet next week.”",
     "options": ["is due", "is about", "is bound", "has"], "answer": 0,
     "explanation": "“Be due to” = scheduled/expected."},
    {"tier": 5, "prompt": "“She left the company ___ good terms.”",
     "options": ["on", "in", "with", "at"], "answer": 0,
     "explanation": "The phrase is “on good terms”."},
    {"tier": 5, "prompt": "“I ___ to seeing you again soon.”",
     "options": ["look forward", "look up", "look out", "look after"], "answer": 0,
     "explanation": "“Look forward to” + -ing."},
    {"tier": 5, "prompt": "“The meeting was called ___ due to the weather.”",
     "options": ["off", "up", "in", "on"], "answer": 0,
     "explanation": "“Call off” = cancel."},
    {"tier": 5, "prompt": "“He takes ___ his father.”",
     "options": ["after", "over", "up", "on"], "answer": 0,
     "explanation": "“Take after” = resemble a family member."},
    {"tier": 5, "prompt": "“I can't make ___ what he said.”",
     "options": ["out", "up", "off", "in"], "answer": 0,
     "explanation": "“Make out” = manage to understand/see."},
    {"tier": 5, "prompt": "“We ran ___ of time.”",
     "options": ["out", "up", "off", "over"], "answer": 0,
     "explanation": "“Run out of” = have none left."},
    {"tier": 5, "prompt": "“She's really come ___ well since last year.”",
     "options": ["on", "up", "off", "over"], "answer": 0,
     "explanation": "“Come on” = progress/improve."},
    {"tier": 5, "prompt": "“The new evidence bears ___ the theory.”",
     "options": ["out", "in", "up", "down"], "answer": 0,
     "explanation": "“Bear out” = confirm/support."},
    {"tier": 5, "prompt": "“He's been promoted ___ manager.”",
     "options": ["to", "as", "for", "with"], "answer": 0,
     "explanation": "“Promote someone to + a position.”"},
    {"tier": 5, "prompt": "“The two companies have ___ forces.”",
     "options": ["joined", "made", "taken", "put"], "answer": 0,
     "explanation": "“Join forces” = work together."},
    {"tier": 5, "prompt": "“There's no ___ in complaining.”",
     "options": ["point", "sense", "reason", "worth"], "answer": 0,
     "explanation": "The phrase is “there's no point in -ing”."},
    {"tier": 5, "prompt": "“I'd sooner ___ than tell a lie.”",
     "options": ["leave", "to leave", "leaving", "left"], "answer": 0,
     "explanation": "“Would sooner” + bare infinitive: “leave”."},
    {"tier": 5, "prompt": "“The situation is getting ___ control.”",
     "options": ["out of", "under", "in", "over"], "answer": 0,
     "explanation": "“Out of control” = not controllable."},
    {"tier": 5, "prompt": "“She has a good ___ for details.”",
     "options": ["eye", "ear", "nose", "hand"], "answer": 0,
     "explanation": "“An eye for detail” = notice small things."},
    {"tier": 5, "prompt": "“He's a man ___ few words.”",
     "options": ["of", "in", "with", "for"], "answer": 0,
     "explanation": "The phrase is “a man of few words” = quiet."},
    {"tier": 5, "prompt": "“The truth finally ___ out.”",
     "options": ["came", "got", "made", "turned"], "answer": 0,
     "explanation": "“Come out” = become known."},
    {"tier": 5, "prompt": "“It goes without ___ that I'll be there.”",
     "options": ["saying", "said", "says", "to say"], "answer": 0,
     "explanation": "The phrase is “it goes without saying”."},
    _q(5, "What does the idiom “a piece of cake” mean?", "something very easy", ("something very hard", "a sweet dessert", "a small problem"), "“A piece of cake” = very easy."),
    _q(5, "What does the idiom “once in a blue moon” mean?", "very rarely", ("very often", "once a month", "never"), "“Once in a blue moon” = extremely rarely."),
    _q(5, "What does the idiom “let the cat out of the bag” mean?", "to reveal a secret", ("to keep a secret", "to feed an animal", "to make a mess"), "It means to accidentally reveal a secret."),
    _q(5, "What does the idiom “beat around the bush” mean?", "to avoid the main point", ("to speak clearly", "to work in a garden", "to win an argument"), "It means to avoid talking directly about something."),
    _q(5, "What does the idiom “hit the nail on the head” mean?", "to be exactly right", ("to miss the point", "to hurt yourself", "to break something"), "It means to describe a situation perfectly."),
    _q(5, "What does the idiom “under the weather” mean?", "slightly ill", ("very happy", "very angry", "caught in the rain"), "It means feeling unwell."),
    _q(5, "What does the idiom “the ball is in your court” mean?", "it's your turn to act", ("you lost the game", "it's too late", "you must leave"), "It means the next move is up to you."),
    _q(5, "What does the idiom “spill the beans” mean?", "to reveal a secret", ("to cook dinner", "to make a mess", "to count carefully"), "It means to tell something that was secret."),
    _q(5, "What does the idiom “break a leg” mean?", "good luck", ("get injured", "work hard", "be careful"), "It is a way to wish someone good luck."),
    _q(5, "What does the idiom “bite the bullet” mean?", "to face something unpleasant bravely", ("to eat quickly", "to run away", "to give up"), "It means to endure something difficult."),
    _q(5, "What does the idiom “cost an arm and a leg” mean?", "to be very expensive", ("to be very cheap", "to be free", "to be useless"), "It means extremely expensive."),
    _q(5, "What does the idiom “cut corners” mean?", "to do something cheaply or quickly", ("to be very careful", "to work slowly", "to spend more money"), "It means to save time/money by lowering quality."),
    _q(5, "What does the idiom “the last straw” mean?", "the final problem that makes a situation unbearable", ("the best part", "the first step", "a lucky break"), "It is the final annoyance that causes a reaction."),
    _q(5, "What does the idiom “get cold feet” mean?", "to become nervous before something", ("to be physically cold", "to run fast", "to feel ill"), "It means to lose confidence right before an event."),
    _q(5, "What does the idiom “pull someone's leg” mean?", "to joke with someone", ("to hurt someone", "to help someone", "to ignore someone"), "It means to tease someone playfully."),
    _q(5, "What does the idiom “go the extra mile” mean?", "to make extra effort", ("to travel far", "to give up", "to be lazy"), "It means to do more than is expected."),
    _q(5, "What does the idiom “sit on the fence” mean?", "to avoid taking a side", ("to relax at home", "to be very busy", "to make a quick decision"), "It means to stay neutral and not decide."),
    _q(5, "What does the idiom “a blessing in disguise” mean?", "something good that seemed bad at first", ("a hidden curse", "a surprise gift", "a lucky coincidence"), "It is a problem that turns out to have a benefit."),
    _q(5, "What does the idiom “add insult to injury” mean?", "to make a bad situation worse", ("to apologize sincerely", "to help generously", "to stay silent"), "It means to worsen an already bad situation."),
    _q(5, "What does the idiom “back to square one” mean?", "to start again from the beginning", ("to finish successfully", "to make progress", "to reach the end"), "It means returning to the starting point."),
    _q(5, "What does the idiom “call it a day” mean?", "to stop working for now", ("to start early", "to work all night", "to change plans"), "It means to finish work for the day."),
    _q(5, "What does the idiom “cut to the chase” mean?", "to get to the point", ("to run away", "to tell a long story", "to end a conversation"), "It means to skip to the important part."),
    _q(5, "What does the idiom “hit the books” mean?", "to study hard", ("to read for fun", "to write a book", "to close a book"), "It means to begin studying seriously."),
    _q(5, "What does the idiom “a wild goose chase” mean?", "a hopeless search", ("a fun adventure", "a quick task", "a successful hunt"), "It means a pointless, futile pursuit."),
    _q(5, "What does the idiom “the tip of the iceberg” mean?", "a small part of a bigger problem", ("the main problem", "the only issue", "a solved mystery"), "It means the visible part of a much larger issue."),
    _q(5, "What does the idiom “burn the midnight oil” mean?", "to work late into the night", ("to waste money", "to relax in the evening", "to sleep early"), "It means to stay up late working or studying."),
    _q(5, "What does the idiom “once bitten, twice shy” mean?", "you are more careful after being hurt", ("you are always brave", "you never learn", "you are very lucky"), "It means an unpleasant experience makes you cautious."),
    _q(5, "What does the idiom “the elephant in the room” mean?", "an obvious problem nobody talks about", ("a big animal", "a fun surprise", "a minor detail"), "It is a sensitive issue everyone avoids."),
    _q(5, "What does the idiom “play devil's advocate” mean?", "to argue the opposite side for debate", ("to lie on purpose", "to praise someone", "to refuse to speak"), "It means to test an idea by arguing against it."),
    _q(5, "What does the idiom “a dime a dozen” mean?", "very common", ("very rare", "very expensive", "very valuable"), "It means common and easy to find."),
    _q(5, "What does “pragmatic” mean?", "practical rather than idealistic", ("dreamy and unrealistic", "angry and harsh", "slow and careful"), "“Pragmatic” = concerned with practical results."),
    _q(5, "What does “eloquent” mean?", "speaking fluently and persuasively", ("speaking quietly", "speaking rudely", "speaking slowly"), "“Eloquent” = expressive and persuasive with words."),
    _q(5, "What does “candid” mean?", "honest and direct", ("secretive and hidden", "rude and loud", "vague and unclear"), "“Candid” = frank, open."),
    _q(5, "What does “skeptical” mean?", "doubtful, not easily convinced", ("easily fooled", "very trusting", "completely certain"), "“Skeptical” = doubting, questioning."),
    _q(5, "What does “reticent” mean?", "not revealing one's thoughts", ("very talkative", "very loud", "very confident"), "“Reticent” = reserved, quiet about one's feelings."),
    _q(5, "What does “tenacious” mean?", "determined and persistent", ("easily giving up", "slow and lazy", "gentle and soft"), "“Tenacious” = holding on firmly, determined."),
    _q(5, "What does “astute” mean?", "sharp and clever at judging", ("slow to understand", "careless with details", "overly trusting"), "“Astute” = shrewd, quick to understand."),
    _q(5, "What does “obsolete” mean?", "no longer used", ("brand new", "very popular", "just invented"), "“Obsolete” = out of date, no longer in use."),
    _q(5, "What does “ephemeral” mean?", "lasting a very short time", ("lasting forever", "very heavy", "very bright"), "“Ephemeral” = short-lived, fleeting."),
    _q(5, "What does “ubiquitous” mean?", "present everywhere", ("found nowhere", "very rare", "hard to see"), "“Ubiquitous” = appearing everywhere."),
    _q(5, "What does “indigenous” mean?", "native to a place", ("foreign to a place", "recently arrived", "artificially made"), "“Indigenous” = originating naturally in a place."),
    _q(5, "What does “salient” mean?", "most important", ("least important", "hard to see", "completely wrong"), "“Salient” = the most noticeable or important."),
    _q(5, "What does “taciturn” mean?", "saying very little", ("very talkative", "very cheerful", "very loud"), "“Taciturn” = habitually quiet, reserved."),
    _q(5, "What does “voracious” mean?", "wanting or eating a lot", ("eating very little", "very picky", "very slow"), "“Voracious” = extremely eager or hungry (e.g. a voracious reader)."),
    _q(5, "What does “prudent” mean?", "careful and sensible", ("rash and careless", "lazy and slow", "proud and rude"), "“Prudent” = wise, cautious."),
    _q(5, "“___ the circumstances, we have no choice.”", "Under", ("In", "With", "Given"), "The fixed phrase is “under the circumstances”."),
    _q(5, "“It's high time you ___ a decision.”", "made", ("make", "have made", "will make"), "“It's (high) time” + past simple."),
    _q(5, "“She was at ___ for what to say.”", "a loss", ("a lose", "loss", "the loss"), "“At a loss for words” = unable to think what to say."),
    _q(5, "“The results are ___ the final report.”", "pending", ("waiting", "depending", "attending"), "“Pending” = awaiting a decision."),
    _q(5, "“The proposal is ___ consideration.”", "under", ("in", "on", "at"), "The phrase is “under consideration”."),
    _q(5, "“He's been promoted ___ manager.”", "to", ("as", "for", "with"), "“Promote someone to + a position”."),
    _q(5, "“The two companies have ___ forces.”", "joined", ("made", "taken", "put"), "“Join forces” = work together."),
    _q(5, "“The situation is getting ___ control.”", "out of", ("under", "in", "over"), "“Out of control” = uncontrollable."),
    _q(5, "“The new evidence bears ___ the theory.”", "out", ("in", "up", "down"), "“Bear out” = confirm, support."),
    _q(5, "Choose the correct sentence.", "It's high time you made a decision.", ("It's high time you make a decision.", "It's high time you have made a decision.", "It's high time you will make a decision."), "“It's high time” + past simple."),
    _q(5, "Choose the correct sentence.", "No sooner had she left than he arrived.", ("No sooner she had left than he arrived.", "No sooner did she left than he arrived.", "No sooner she left than he arrived."), "“No sooner … than” with inversion: “had she left”."),
    _q(5, "Choose the correct sentence.", "Each of the students has a book.", ("Each of the students have a book.", "Each of the students are having a book.", "Each of the students having a book."), "“Each of” takes a singular verb."),
    _q(5, "Choose the correct sentence.", "I'd rather walk than take the bus.", ("I'd rather to walk than take the bus.", "I'd rather walking than take the bus.", "I'd rather walked than take the bus."), "“Would rather” + bare infinitive."),
    _q(5, "Choose the correct sentence.", "There's little point in arguing about it.", ("There's little point to argue about it.", "There's little point of arguing about it.", "There's little point arguing about it."), "The phrase is “there's little point in -ing”."),
    _q(5, "Choose the correct sentence.", "The situation is getting out of control.", ("The situation is getting out control.", "The situation is getting under control.", "The situation is getting out from control."), "“Out of control” is correct."),
    _q(5, "Choose the correct sentence.", "She is cut out for teaching.", ("She is cut out to teaching.", "She is cut out of teaching.", "She is cut out in teaching."), "“Be cut out for” = suited to."),
    _q(5, "Choose the correct sentence.", "Under the circumstances, we have no choice.", ("In the circumstances, we have no choice.", "With the circumstances, we have no choice.", "At the circumstances, we have no choice."), "The fixed phrase is “under the circumstances”."),
    _q(5, "Choose the correct sentence.", "The truth finally came out.", ("The truth finally came up.", "The truth finally came on.", "The truth finally came over."), "“Come out” = become known."),
    _q(5, "Choose the correct sentence.", "I'd sooner leave than tell a lie.", ("I'd sooner to leave than tell a lie.", "I'd sooner leaving than tell a lie.", "I'd sooner left than tell a lie."), "“Would sooner” + bare infinitive."),
    _q(5, "Choose the correct sentence.", "The new evidence bears out the theory.", ("The new evidence bears up the theory.", "The new evidence bears in the theory.", "The new evidence bears down the theory."), "“Bear out” = confirm."),
    _q(5, "Choose the correct sentence.", "He's a man of few words.", ("He's a man in few words.", "He's a man with few words.", "He's a man at few words."), "The phrase is “a man of few words”."),
    _q(5, "Choose the correct sentence.", "She has a good eye for details.", ("She has a good eye in details.", "She has a good eye on details.", "She has a good eye at details."), "“An eye for detail” is correct."),
    _q(5, "Choose the correct sentence.", "The committee is due to meet next week.", ("The committee is about to meet next week.", "The committee is bound to meet next week.", "The committee is due meeting next week."), "“Be due to” = scheduled."),
    _q(5, "Choose the correct sentence.", "He keeps his head above water.", ("He keeps his head over water.", "He keeps his head up water.", "He keeps his head on water."), "“Keep one's head above water” is the idiom."),
    _q(5, "What does “exacerbate” mean?", "to make something worse", ("to make something better", "to hide something", "to forget something"), "“Exacerbate” = make a problem worse."),

    # =====================================================================
    # Доп. блок: артикли (a/an · the vs a/an · нулевой артикль) — все тиры
    # =====================================================================
    # --- тир 1: a / an ---
    _q(1, "“She is ___ teacher.”", "a", ("an", "the", "—"), "“Teacher” starts with a consonant sound → “a”."),
    _q(1, "“It's ___ easy question.”", "an", ("a", "the", "—"), "“Easy” starts with a vowel sound → “an”."),
    _q(1, "“He lives in ___ old house.”", "an", ("a", "the", "—"), "“Old” starts with a vowel sound → “an”."),
    _q(1, "“I saw ___ bird in the tree.”", "a", ("an", "the", "—"), "“Bird” starts with a consonant sound → “a”."),
    _q(1, "“She has ___ umbrella.”", "an", ("a", "the", "—"), "“Umbrella” starts with a vowel sound → “an”."),
    _q(1, "“He is ___ university student.”", "a", ("an", "the", "—"), "“University” starts with the /j/ consonant sound → “a”."),
    _q(1, "“It's ___ hour until the show.”", "an", ("a", "the", "—"), "“Hour” has a silent h, so it starts with a vowel sound → “an”."),
    _q(1, "“We need ___ new table.”", "a", ("an", "the", "—"), "“New” starts with a consonant sound → “a”."),

    # --- тир 2: the vs a/an ---
    _q(2, "“___ sun rises in the east.”", "The", ("A", "An", "—"), "Unique things take “the”: the sun."),
    _q(2, "“She's ___ best student in class.”", "the", ("a", "an", "—"), "Superlatives take “the”: the best."),
    _q(2, "“I saw a cat. ___ cat was black.”", "The", ("A", "An", "—"), "Second mention → “the” (we know which cat)."),
    _q(2, "“He plays ___ guitar.”", "the", ("a", "an", "—"), "Musical instruments take “the”: the guitar."),
    _q(2, "“___ Nile is a long river.”", "The", ("A", "An", "—"), "Rivers take “the”: the Nile."),
    _q(2, "“She works in ___ office.”", "an", ("a", "the", "—"), "“Office” starts with a vowel sound → “an”."),
    _q(2, "“This is ___ first time I've been here.”", "the", ("a", "an", "—"), "Ordinals take “the”: the first time."),
    _q(2, "“I want to be ___ engineer.”", "an", ("a", "the", "—"), "“Engineer” starts with a vowel sound → “an”."),
    _q(2, "“Can you close ___ door, please?”", "the", ("a", "an", "—"), "We both know which door → “the”."),
    _q(2, "“___ Alps are in Europe.”", "The", ("A", "An", "—"), "Mountain ranges take “the”: the Alps."),

    # --- тир 3: нулевой артикль + the ---
    _q(3, "“I have ___ breakfast at eight.”", "—", ("a", "an", "the"), "Meals take no article: have breakfast."),
    _q(3, "“She studies ___ mathematics at university.”", "—", ("a", "an", "the"), "School subjects take no article."),
    _q(3, "“He went to ___ bed early.”", "—", ("a", "an", "the"), "“Go to bed” (the activity) → no article."),
    _q(3, "“They live in ___ France.”", "—", ("a", "an", "the"), "Most countries take no article."),
    _q(3, "“She speaks ___ Spanish fluently.”", "—", ("a", "an", "the"), "Languages take no article."),
    _q(3, "“I play ___ football on Saturdays.”", "—", ("a", "an", "the"), "Sports take no article."),
    _q(3, "“___ love is all you need.”", "—", ("A", "An", "The"), "Abstract nouns in general → no article."),
    _q(3, "“___ information you gave me was useful.”", "The", ("A", "An", "—"), "Specific information → “the”."),
    _q(3, "“She is ___ only person I trust.”", "the", ("a", "an", "—"), "“The only” is a fixed phrase."),
    _q(3, "“He was sent to ___ prison for the crime.”", "—", ("a", "an", "the"), "“Sent to prison” (as a punishment) → no article."),

    # --- тир 4: устойчивые выражения ---
    _q(4, "“___ more you read, the more you know.”", "The", ("A", "An", "—"), "Comparative structure: “the more … the more”."),
    _q(4, "“She has ___ good knowledge of English.”", "a", ("an", "the", "—"), "“A good knowledge of” is a fixed phrase."),
    _q(4, "“We had ___ lunch at noon.”", "—", ("a", "an", "the"), "Meals take no article: had lunch."),
    _q(4, "“He's ___ honorable man.”", "an", ("a", "the", "—"), "“Honorable” has a silent h → “an”."),
    _q(4, "“___ Amazon is the longest river.”", "The", ("A", "An", "—"), "Rivers take “the”: the Amazon."),
    _q(4, "“She's ___ CEO of a big company.”", "the", ("a", "an", "—"), "A unique role → “the CEO”."),
    _q(4, "“I saw ___ film you recommended.”", "the", ("a", "an", "—"), "A specific, known film → “the”."),
    _q(4, "“He's on ___ phone right now.”", "the", ("a", "an", "—"), "Fixed phrase: “on the phone”."),
    _q(4, "“This is ___ very interesting book.”", "a", ("an", "the", "—"), "“A + adjective + singular noun”."),

    # --- тир 5: тонкости ---
    _q(5, "“___ rich should help the poor.”", "The", ("A", "An", "—"), "“The + adjective” = a group of people."),
    _q(5, "“He is ___ man of great courage.”", "a", ("an", "the", "—"), "“A man of …” → indefinite article."),
    _q(5, "“She's ___ teacher, and she loves her job.”", "a", ("an", "the", "—"), "Professions take “a/an”."),
    _q(5, "“___ United States is a big country.”", "The", ("A", "An", "—"), "Countries with “States/Kingdom/Republic” take “the”."),
    _q(5, "“It was ___ honour to meet you.”", "an", ("a", "the", "—"), "“Honour” has a silent h → “an”."),
    _q(5, "“We visited ___ Netherlands last year.”", "the", ("a", "an", "—"), "Some country names (plural) take “the”."),
    _q(5, "“He's ___ heir to the throne.”", "an", ("a", "the", "—"), "“Heir” has a silent h → “an”."),
    _q(5, "“___ Atlantic Ocean is very deep.”", "The", ("A", "An", "—"), "Oceans take “the”: the Atlantic Ocean."),
]


def pick_millionaire_game() -> list[dict]:
    """Выбрать 15 вопросов: по 3 случайных из каждого тира, в порядке роста сложности.

    Вопросы не повторяются внутри одной партии (sample без замены). Если в тире
    вдруг меньше вопросов, чем QUESTIONS_PER_TIER, берём сколько есть.
    """
    picked: list[dict] = []
    for tier in range(1, TOTAL_TIERS + 1):
        pool = [q for q in MILLIONAIRE_QUESTIONS if q["tier"] == tier]
        picked.extend(random.sample(pool, min(QUESTIONS_PER_TIER, len(pool))))
    return picked
