"""Банк слов для игры Wordle.

Список распространённых английских слов из 5 букв (американская орфография),
используются как загадываемое слово. Хелпер `random_wordle_word()` возвращает
случайное слово.
"""
import random

WORDLE_WORDS: list[str] = [
    "about", "above", "abuse", "actor", "adapt", "admit", "adopt", "adult", "after", "again",
    "agent", "agree", "ahead", "alarm", "album", "alien", "align", "allow", "alone", "along",
    "alter", "among", "anger", "angle", "angry", "ankle", "apart", "apple", "apply", "arena",
    "argue", "arise", "armed", "arrow", "aside", "asset", "atlas", "audio", "avoid", "award",
    "aware", "awful",
    "bacon", "badge", "baker", "basic", "basis", "batch", "beach", "beard", "beast", "begin",
    "being", "below", "bench", "berry", "birth", "black", "blade", "blame", "blank", "blast",
    "blend", "blind", "block", "blood", "bloom", "board", "boost", "booth", "bound", "brain",
    "brand", "brave", "bread", "break", "breed", "brick", "bride", "brief", "bring", "broad",
    "broke", "brown", "brush", "build", "built", "bunch", "burst", "buyer",
    "cabin", "cable", "camel", "canal", "candy", "cargo", "carry", "catch", "cause", "chain",
    "chair", "chalk", "champ", "chaos", "charm", "chart", "chase", "cheap", "check", "cheek",
    "chest", "chief", "child", "chill", "choir", "chunk", "civic", "civil", "claim", "clash",
    "class", "clean", "clear", "clerk", "click", "cliff", "climb", "clock", "close", "cloth",
    "cloud", "coach", "coast", "color", "comic", "count", "court", "cover", "crack", "craft",
    "crash", "crazy", "cream", "crime", "crisp", "cross", "crowd", "crown", "crude", "cruel",
    "crush", "curve", "cycle",
    "daily", "dance", "death", "debut", "delay", "delta", "dense", "depth", "devil", "diary",
    "dirty", "ditch", "diver", "dizzy", "doubt", "dough", "dozen", "draft", "drama", "dream",
    "dress", "drill", "drink", "drive", "drove", "drunk", "dying",
    "eagle", "early", "earth", "eight", "elbow", "elite", "email", "empty", "enemy", "enjoy",
    "enter", "entry", "equal", "error", "essay", "event", "every", "exact", "exist", "extra",
    "fairy", "faith", "false", "fancy", "fatal", "fault", "favor", "feast", "fence", "fever",
    "fiber", "field", "fifth", "fifty", "fight", "final", "first", "flame", "flash", "flesh",
    "float", "flood", "floor", "flour", "focus", "force", "forge", "forth", "forty", "forum",
    "found", "frame", "fresh", "front", "frost", "fruit", "funny",
    "gauge", "ghost", "giant", "given", "glass", "globe", "glory", "glove", "going", "grace",
    "grade", "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grave", "great",
    "green", "greet", "grief", "grill", "grind", "groan", "gross", "group", "grove", "grown",
    "guard", "guess", "guest", "guide",
    "habit", "happy", "harsh", "haste", "heart", "heavy", "hedge", "hello", "hence", "hobby",
    "honey", "honor", "horse", "hotel", "house", "human", "humor", "hurry",
    "ideal", "image", "imply", "index", "inner", "input", "issue", "ivory",
    "jewel", "joint", "judge", "juice",
    "knife", "knock", "known",
    "label", "labor", "large", "laser", "later", "laugh", "layer", "learn", "lease", "least",
    "leave", "legal", "lemon", "level", "light", "limit", "linen", "liver", "local", "logic",
    "loose", "lower", "loyal", "lunch",
    "magic", "major", "maker", "maple", "march", "marry", "match", "mayor", "maybe", "medal",
    "media", "mercy", "merge", "merit", "metal", "meter", "might", "minor", "model", "money",
    "month", "moral", "motor", "mount", "mouse", "mouth", "movie", "music",
    "naked", "nerve", "never", "newly", "night", "ninth", "noble", "noise", "north", "novel",
    "nurse",
    "occur", "ocean", "offer", "often", "onion", "opera", "order", "organ", "other", "outer",
    "owner",
    "paint", "panel", "panic", "paper", "party", "pasta", "patch", "pause", "peace", "peach",
    "pearl", "penny", "phase", "phone", "photo", "piano", "piece", "pilot", "pitch", "pivot",
    "place", "plain", "plane", "plant", "plate", "plaza", "point", "polar", "pound", "power",
    "press", "price", "pride", "prime", "print", "prior", "prize", "proof", "proud", "prove",
    "pupil",
    "queen", "quick", "quiet", "quite", "quote",
    "radar", "radio", "raise", "ranch", "range", "rapid", "ratio", "reach", "react", "ready",
    "realm", "rebel", "refer", "relax", "reply", "right", "rigid", "rival", "river", "roast",
    "robot", "rocky", "rough", "round", "route", "royal", "ruler", "rural",
    "saint", "salad", "sauce", "scale", "scene", "scent", "scope", "score", "scout", "screw",
    "sense", "serve", "seven", "shade", "shake", "shall", "shame", "shape", "share", "sharp",
    "sheep", "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock", "shoot", "shore",
    "short", "shout", "sight", "since", "sixth", "sixty", "skill", "sleep", "slice", "slide",
    "small", "smart", "smell", "smile", "smoke", "snake", "solar", "solid", "solve", "sorry",
    "sound", "south", "space", "spare", "spark", "speak", "speed", "spell", "spend", "spice",
    "spill", "spine", "split", "spoon", "sport", "spray", "sprig", "squad", "stack", "staff",
    "stage", "stain", "stair", "stake", "stamp", "stand", "stare", "start", "state", "steel",
    "steep", "steer", "stick", "stiff", "still", "stock", "stone", "stood", "store", "storm",
    "story", "stove", "strap", "straw", "strip", "stuck", "study", "stuff", "style", "sugar",
    "suite", "sunny", "super", "surge", "swear", "sweat", "sweep", "sweet", "swell", "swift",
    "swing", "sword",
    "table", "taste", "teach", "teeth", "tense", "thank", "theft", "theme", "there", "thick",
    "thief", "thing", "think", "third", "thorn", "those", "three", "threw", "throw", "thumb",
    "tiger", "tight", "timer", "title", "toast", "today", "token", "topic", "total", "touch",
    "tough", "tower", "trace", "track", "trade", "trail", "train", "trait", "trash", "treat",
    "trend", "trial", "tribe", "trick", "troop", "truck", "truly", "trunk", "trust", "truth",
    "tutor", "twice",
    "uncle", "under", "union", "unite", "unity", "until", "upper", "upset", "urban", "usage",
    "usual",
    "valid", "value", "vault", "venue", "verse", "video", "vigor", "villa", "vinyl", "virus",
    "visit", "vital", "vivid", "vocal", "voice", "voter",
    "wagon", "waist", "watch", "water", "weave", "weary", "weird", "whale", "wheat", "wheel",
    "where", "which", "while", "white", "whole", "whose", "widow", "width", "witch", "woman",
    "women", "world", "worry", "worse", "worst", "worth", "would", "wound", "wrist", "write",
    "wrong", "wrote",
    "yacht", "yeast", "yield", "young", "youth",
]


def random_wordle_word() -> str | None:
    """Случайное 5-буквенное слово, либо None, если банк пуст."""
    return random.choice(WORDLE_WORDS) if WORDLE_WORDS else None
